# Generated by Django 4.2.11 on 2024-05-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата производства продукта"
            ),
        ),
    ]
