# Generated by Django 4.2.2 on 2024-06-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_article_product_creator_product_views_counter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_unpublish_product', 'Can unpublish a product'), ('can_edit_description', 'Can edit the description of any product'), ('can_change_category', 'Can change the category of any product')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='published',
            field=models.BooleanField(blank=True, default=False, verbose_name='Опубликована'),
        ),
    ]
