# Generated by Django 5.0.6 on 2024-06-21 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.PositiveIntegerField(default=1, help_text='Укажите номер версии.', verbose_name='Номер версии')),
                ('title', models.CharField(blank=True, help_text='Введите название версии.', max_length=50, null=True, verbose_name='Название версии')),
                ('currented', models.BooleanField(blank=True, verbose_name='Текущая версия')),
                ('product', models.ForeignKey(blank=True, help_text='Продукты данной версии:', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='catalog.product', verbose_name='Продукты данной версии')),
            ],
            options={
                'verbose_name': 'версия',
                'verbose_name_plural': 'версии',
            },
        ),
    ]
