# Generated by Django 4.2.2 on 2024-06-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_options_product_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_publish_product', 'Can publish a product'), ('can_edit_description', 'Can edit the description of any product'), ('can_change_category', 'Can change the category of any product')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
