# Generated by Django 4.2.2 on 2024-06-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_image_alter_product_title_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Добавьте изображение продукта.', null=True, upload_to='catalog/image', verbose_name='Изображение продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, help_text='Введите наименование продукта.', max_length=50, null=True, verbose_name='Наименование'),
        ),
    ]
